### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by xoviat** [jcfr/VTKPythonPackage#1]
@jcfr If you attach Travis, I can spam the builds until I get something working.

**Comment by jcfr** [comment]
Thanks for your help.

All set. See https://travis-ci.org/jcfr/VTKPythonPackage

A working configuration (for smaller project) has been to use:
* travis for macosx
* circleci for linux build (using the manylinux images)
* appveyor for windows wheels

Worth noting that using these two packages allows us to streamline the process across the three platforms:
* [scikit-ci](scikit-ci.readthedocs.io)
* [scikit-ci-addons](scikit-ci-addons.readthedocs.io)

Here are example of project leveraging these CI services:
* https://github.com/scikit-build/cmake-python-distributions
* https://github.com/QIICR/dcmqi
