### ISSUE TITLE
Add wheel for python 3.8 to pypi

### ISSUE THREAD

**Issue by skoudoro** [jcfr/VTKPythonPackage#39]
Hello, 

Currently, PyPI lists 2.7, 3.5, 3.6 and 3.7 wheels for VTK 8.1.2. is it possible to have 3.8 wheels for the supported platforms? 

Can you provide wheels for VTK 8.2.0 too? 

Thank you

**Comment by jcfr** [comment]
Hi, 

We are currently working on updating VTK and will plan on publishing wheels for VTK 9.0. See https://gitlab.kitware.com/vtk/vtk/merge_requests/5543

We currently do not plan to provide wheels for VTK 8.2

**Comment by skoudoro** [comment]
ok, thank you and good job to the team for that!

By curiosity, is there an ETA?

**Comment by jcfr** [comment]
This is pending few tasks:
* finalize work associated with this issue and release of python versions integrating the change. See https://bugs.python.org/issue38728
* update our internal continuous integration infrastructure to test wheel generation

We expect this to be done by end of Q1 2020

**Comment by jcfr** [comment]
For reference:

![image](https://user-images.githubusercontent.com/219043/101668123-276fcb80-3a1e-11eb-90b6-de1af00aff50.png)

See https://pypi.org/project/vtk/#files

**Comment by skoudoro** [comment]
yes, thanks @jcfr!  this is why I closed this issue 👍🏾
