### ISSUE TITLE
python wheel: How to compile the qt GUI for vtk’s git master version on Ubuntu 20.04.

### ISSUE THREAD

**Issue by hongyi-zhao** [jcfr/VTKPythonPackage#44]
Hi,

I asked this issue [here](https://discourse.vtk.org/t/how-to-compile-the-qt-gui-for-vtks-git-master-version-on-ubuntu-20-04/3529) but no answer has been given till now.

Could someone here please give me some hints?

Regards

**Comment by jcfr** [comment]
Thanks for reaching out, I will close this issue and provide some feedback on  discourse.

**Comment by jcfr** [comment]
Could you rename your topic from

`How to compile the qt GUI for vtk’s git master version on Ubuntu 20.04.`

to 

`python wheel: How to compile the qt GUI for vtk’s git master version on Ubuntu 20.04.`

**Comment by jcfr** [comment]
Could you also apply the change on discourse?  https://discourse.vtk.org/t/how-to-compile-the-qt-gui-for-vtks-git-master-version-on-ubuntu-20-04/3529

**Comment by hongyi-zhao** [comment]
@jcfr Done.
