### ISSUE TITLE
I want to know how to keep the original mark after reading the image

### ISSUE THREAD

**Issue by hulihan-start** [jcfr/VTKPythonPackage#49]
I want to know how to keep the original mark after reading the image. There is no color mark when the image is reconstructed in 3D :(

**Comment by hulihan-start** [comment]
by the way, I'm using vtk.vtkNIFTIImageReader() to read the nifty image and want to reconstruct it in 3D

**Comment by jcfr** [comment]
Thanks  for reaching out, to ensure your question reach the appropriate audience, could you post it on the VTK forum. See https://discourse.vtk.org/

In the meantime, I am closing this issue.
